# Generated by Django 3.2.8 on 2022-11-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('role_director', models.BooleanField(verbose_name='Роль руководителя')),
                ('role_tutor', models.BooleanField(verbose_name='Роль куратора')),
                ('role_intern', models.BooleanField(default=True, verbose_name='Роль стажёра')),
                ('mail', models.EmailField(max_length=250, unique=True, verbose_name='Почта')),
                ('password', models.CharField(blank=True, max_length=10, null=True, verbose_name='Пароль')),
                ('educational_institution', models.CharField(blank=True, max_length=500, null=True, verbose_name='Университет')),
                ('specialization', models.CharField(blank=True, max_length=500, null=True, verbose_name='Специальность')),
                ('course', models.CharField(blank=True, max_length=2, null=True, verbose_name='Курс обучения')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на телеграмм')),
                ('vk', models.URLField(blank=True, null=True, verbose_name='Ссылка на VK')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название критерия оценки')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценки',
                'db_table': 'evaluationсriteria',
            },
        ),
        migrations.CreateModel(
            name='EventUts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'event_uts',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('id_event', models.ForeignKey(db_column='id_event', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.eventuts', verbose_name='Название мероприятия')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название этапа')),
                ('active', models.BooleanField(verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Этап оценивания',
                'verbose_name_plural': 'Этапы оценивания',
                'db_table': 'stage',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uralapi.customer', verbose_name='Пользователь')),
                ('role_director', models.CharField(max_length=100, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uralapi.customer', verbose_name='Пользователь')),
                ('role_intern', models.CharField(max_length=100, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Стажёр',
                'verbose_name_plural': 'Стажёры',
                'db_table': 'intern',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='uralapi.customer', verbose_name='Пользователь')),
                ('role_tutor', models.CharField(blank=True, max_length=100, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название команды')),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.project', verbose_name='Название проекта')),
                ('id_tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.tutor', verbose_name='Куратор')),
                ('participants', models.ManyToManyField(blank=True, to='uralapi.Intern', verbose_name='Стажёры')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='StageTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_stage', models.ForeignKey(db_column='id_stage', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.stage', verbose_name='Этап')),
                ('id_team', models.ForeignKey(db_column='id_team', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.team', verbose_name='Название команды')),
            ],
            options={
                'verbose_name': 'Этап / Команда',
                'verbose_name_plural': 'Этапы / Команды',
                'db_table': 'stage_team',
                'unique_together': {('id_team', 'id_stage')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='id_director',
            field=models.ForeignKey(db_column='id_director', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.director', verbose_name='Руководитель'),
        ),
        migrations.CreateModel(
            name='EvaluationCriteriaStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evaluationCriteria', models.ForeignKey(db_column='id_evaluationСriteria', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.evaluationcriteria', verbose_name='Критерий оценки')),
                ('id_stage', models.ForeignKey(db_column='id_stage', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.stage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Критерий оценки / Этап',
                'verbose_name_plural': 'Критерии оценки / Этапы',
                'db_table': 'evaluationсriteria_stage',
                'unique_together': {('id_stage', 'id_evaluationCriteria')},
            },
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_appraiser', models.IntegerField(verbose_name='Оценщик')),
                ('customer_role', models.CharField(max_length=23, verbose_name='Роль пользователя')),
                ('time_voting', models.DateTimeField(auto_now=True, verbose_name='Время голосования')),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.project', verbose_name='Проект')),
                ('id_stage', models.ForeignKey(db_column='id_stage', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.stage', verbose_name='Этап')),
                ('id_team', models.ForeignKey(db_column='id_team', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.team', verbose_name='Команда')),
                ('id_intern', models.ForeignKey(db_column='id_intern', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.intern', verbose_name='Стажёр')),
            ],
            options={
                'verbose_name': 'Собранная оценка',
                'verbose_name_plural': 'Собранные оценки',
                'db_table': 'estimation',
            },
        ),
        migrations.CreateModel(
            name='InternTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_team', models.ForeignKey(db_column='id_team', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.team', verbose_name='Команда')),
                ('id_intern', models.ForeignKey(db_column='id_intern', on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.intern', verbose_name='Стажёр')),
            ],
            options={
                'verbose_name': 'Стажёр / Команда',
                'verbose_name_plural': 'Стажёры / Команды',
                'db_table': 'intern_team',
                'unique_together': {('id_team', 'id_intern')},
            },
        ),
    ]
