# Generated by Django 3.2.8 on 2022-12-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uralapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='stages',
        ),
        migrations.AlterField(
            model_name='stage',
            name='evaluation_criteria',
            field=models.ManyToManyField(default=(), to='uralapi.EvaluationCriteria', verbose_name='Критерии оценки'),
        ),
    ]
