# Generated by Django 3.2.8 on 2022-12-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uralapi', '0002_auto_20221210_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='id_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='uralapi.team', verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='evaluation_criteria',
            field=models.ManyToManyField(default=(), to='uralapi.EvaluationCriteria', verbose_name='Критерии оценки'),
        ),
    ]
