# Generated by Django 3.2.8 on 2023-03-13 16:42

from django.db import migrations, models
import uralapi.functions


class Migration(migrations.Migration):

    dependencies = [
        ('uralapi', '0002_auto_20230221_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to=uralapi.functions.upload_to, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='evaluation_criteria',
            field=models.ManyToManyField(default=(), to='uralapi.EvaluationCriteria', verbose_name='Критерии оценки'),
        ),
    ]
