# Generated by Django 3.2.8 on 2022-12-10 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uralapi', '0003_auto_20221210_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='competence1',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(3)], verbose_name='Вовлеченность'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='competence2',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(3)], verbose_name='Организованность'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='competence3',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(3)], verbose_name='Обучаемость'),
        ),
        migrations.AddField(
            model_name='estimation',
            name='competence4',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(3)], verbose_name='Командность'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='evaluation_criteria',
            field=models.ManyToManyField(default=(), to='uralapi.EvaluationCriteria', verbose_name='Критерии оценки'),
        ),
    ]
