# Generated by Django 4.1.2 on 2022-11-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('role_director', models.IntegerField()),
                ('role_tutor', models.IntegerField()),
                ('role_intern', models.IntegerField()),
                ('mail', models.CharField(max_length=400, unique=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_appraiser', models.IntegerField()),
                ('customer_role', models.CharField(max_length=23)),
                ('time_voting', models.DateTimeField()),
            ],
            options={
                'db_table': 'estimation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'evaluationсriteria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventUts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_uts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lk_trainee.customer')),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationCriteriaStage',
            fields=[
                ('id_stage', models.OneToOneField(db_column='id_stage', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lk_trainee.stage')),
            ],
            options={
                'db_table': 'evaluationсriteria_stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lk_trainee.customer')),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'intern',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternTeam',
            fields=[
                ('id_team', models.OneToOneField(db_column='id_team', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lk_trainee.team')),
            ],
            options={
                'db_table': 'intern_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StageTeam',
            fields=[
                ('id_team', models.OneToOneField(db_column='id_team', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lk_trainee.team')),
            ],
            options={
                'db_table': 'stage_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lk_trainee.customer')),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
    ]
